# Generated by Django 4.2.1 on 2023-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
