# Generated by Django 4.2.1 on 2023-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(default=True, max_length=2500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
